gluonhq/gluonfx-gradle-plugin

- .travis.yml
- build.gradle
This pipeline deploys to:
* Gluon Nexus public snapshot repository for each commit 
* Gluon Nexus release repository for each tag
> Enable Travis CI

- README.md
Adds badges to ReadME for build status and license.
> Add badges to ReadME

- src/main/java/com/gluonhq/gradle/ClientExtension.java
> use Java 11 (ea+2 for now) as baseline

- build.gradle
- src/main/java/com/gluonhq/gradle/ClientExtension.java
> Use new GraalVM build by default (20.0.0-ea+15)

- src/main/java/com/gluonhq/gradle/tasks/ClientNativeInstall.java
- src/main/java/com/gluonhq/gradle/tasks/ClientNativeLink.java
- src/main/java/com/gluonhq/gradle/tasks/ClientNativePackage.java
- src/main/java/com/gluonhq/gradle/tasks/ConfigBuild.java
From gluonhq@1e56a6c0e3e48038dc4ab081d811d9e1b865685b
> Package and install tasks fail when substrate call fails

- .ci/release.sh
After a release we would like:
1. `build.gradle` to be automatically updated to next SNAPSHOT version
2. Update `README.md` to latest release version
> Update to release process

- .ci/update-ide-properties.sh
- .travis.yml
Also, updated AWS configuration in Travis settings.
> Install awscli using Travis addons

- .ci/release.sh
- build.gradle
PUBLISH_KEY and PUBLISH_SECRET have been added to Travis
> Publish to Gradle plugin repository

- src/main/java/com/gluonhq/gradle/attach/AttachServiceDefinition.java
> Add Linux AArch64 to supported platform

- README.md
- src/main/java/com/gluonhq/gradle/ClientExtension.java
- src/main/java/com/gluonhq/gradle/ClientPlugin.java
- src/main/java/com/gluonhq/gradle/attach/AttachConfiguration.java
- src/main/java/com/gluonhq/gradle/tasks/ClientNativeInstall.java
- src/main/java/com/gluonhq/gradle/tasks/ClientNativeLink.java
- src/main/java/com/gluonhq/gradle/tasks/ClientNativePackage.java
- src/main/java/com/gluonhq/gradle/tasks/ConfigBuild.java
Contains the following changes:
* Replace TABS with SPACES
* Update README.md
* Update license header
> Random fixes

- README.md
- build.gradle
- settings.gradle
- src/main/java/com/gluonhq/gradle/GluonFXPlugin.java
- src/main/java/com/gluonhq/gradle/tasks/ConfigBuild.java
- src/main/java/com/gluonhq/gradle/tasks/NativeBaseTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeBuildTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeCompileTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeInstallTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeLinkTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativePackageTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeRunAgentTask.java
- src/main/java/com/gluonhq/gradle/tasks/NativeRunTask.java
Rename plugin to `gluonfx-gradle-plugin` and bumps the current development version to `0.9.0`.
> Rename Client to GluonFX

- README.md
- src/main/java/com/gluonhq/gradle/ClientExtension.java
> Update readme with Configuration

- .github/release-drafter.yml
- .github/workflows/build.yml
Maintains a draft release-note for every new release
> Draft releases via release-drafter action

- .github/scripts/update-ide-properties.sh
Related to https://github.com/aws/aws-cli/issues/5262
> Add region to aws command

- src/main/java/com/gluonhq/gradle/attach/AttachConfiguration.java
> Use iOS classifier for the iOS simulator

- src/main/java/com/gluonhq/gradle/ClientExtension.java
- src/main/java/com/gluonhq/gradle/tasks/ConfigBuild.java
Fixes #99 at least for the package name/application identifier. 
Other platform variables can be already set with ReleaseConfiguration.
> Allow configurable app Id

- .github/scripts/update-ide-properties.sh
With new release of plugin templates, the location of the settings file has been updated.
> Update location for settings

- src/main/java/com/gluonhq/gradle/tasks/NativeRunAgentTask.java
> Filter out Windows classes

- src/main/java/com/gluonhq/gradle/tasks/NativeRunAgentTask.java
> Improve runagent filter

- src/main/java/com/gluonhq/gradle/ReleaseConfiguration.java
Adds version and updates appDescription to description.
> Update ReleaseConfiguration with generic variables

- src/main/java/com/gluonhq/gradle/attach/AttachService.java
> Add support for StoreReview service

- src/main/java/com/gluonhq/gradle/tasks/NativeRunAgentTask.java
> Add correct binary name to native agent task
